include:
  - project: 'cncf/gitlab-ci-template'
    ref: master
    file: 'template/backend-java-v2.yaml'
variables:
  APP_NAME: pipeline-master-app
  ARTIFACT_PATH: pipeline-project/pipeline-master-app/target/pipeline-master-app-ark-biz.jar